---
title: "Work and Corona dashboard aggregation of ACPP data"
author: "Fabian Kalleitner"
date: "12/12/2022"
output:
  html_document:
    df_print: paged
    toc: true
---

```{r setup, include=FALSE}

library("tidyverse")
library("srvyr")
library("panelr")

knitr::opts_chunk$set(
  warning = TRUE, 
  message = TRUE, 
  error = TRUE, 
                
  echo = TRUE  
)
ggplot2::theme_set(ggplot2::theme_bw())
pander::panderOptions("table.split.table", Inf)

```

## TODO

- English dashboard


```{r data import and sociodem, include = FALSE}

#import ACPP data in long format
bern_data_long2_factored = readRDS("./../../R/W1-33_CORONAPANEL_recoded.rds")

#import reverse information (which variable scales to reverse [handcoded!])
rev_labels<-readr::read_csv("./output/tables/varlabels_rev_2.csv",show_col_types = FALSE)

##############################
#RECODING
##############################

#create wave variable in data format
bern_data_long2_factored$wavedate <- as_factor(as.character(bern_data_long2_factored$wave))

#input median date of interview to wavedate for every survey wave
#median(as.Date(bern_data_long2_factored$START_DATE[bern_data_long2_factored$wave==24],"%y-%m-%d"),na.rm=TRUE)

levels(bern_data_long2_factored$wavedate) <-c("28.03.2020", "04.04.2020", "11.04.2020","17.04.2020","25.04.2020",
                                              "03.05.2020","09.05.2020","16.05.2020","24.05.2020","29.05.2020",
                                              "13.06.2020","27.06.2020","11.07.2020","15.08.2020","12.09.2020",
                                              "17.10.2020","14.11.2020","13.12.2020","16.01.2021","13.02.2021",
                                              "13.03.2021","16.04.2021","22.05.2021","26.06.2021","25.09.2021",
                                              "23.10.2021","26.11.2021","14.01.2022","18.02.2022","18.03.2022",
                                              "22.04.2022","21.05.2022","21.10.2022")
bern_data_long2_factored$wavedate = as.Date(bern_data_long2_factored$wavedate, "%d.%m.%Y")

#SOCIODEMOGRAPHICS--------------------------------------------------------------

#EDUCATION LEVEL------------------------

bern_data_long2_factored <- bern_data_long2_factored %>% mutate( 
  edu4= ifelse(SD_EDU == "Volksschule oder weniger" | SD_EDU == "Hauptschule oder AHS Unterstufe" | SD_EDU == "Polytechnikum, BMS (Fachschule, z.B. HASCH)", "primary",
         ifelse(SD_EDU == "Lehre, Berufsschule", "Lehre", 
         ifelse(SD_EDU == "AHS mit Matura" | SD_EDU == "BHS mit Matura (z.B. HTL, HAK, HBLA etc.)" | SD_EDU == "Hochschulverwandte Lehranstalt oder Kolleg", "secondary",
        ifelse(SD_EDU == "Bachelor" | SD_EDU == "Magister / Master / Diplomingenieur / Fachhochschule" | SD_EDU == "Doktor / PhD", "tertiary",NA)))))

bern_data_long2_factored$edu4 <- as.factor(bern_data_long2_factored$edu4)

bern_data_long2_factored$edu4 <- fct_relevel(bern_data_long2_factored$edu4, "primary","Lehre","secondary","tertiary" )

#AGE GROUP------------------------------

bern_data_long2_factored <- bern_data_long2_factored %>% mutate(alter=2020-SD_BIRTHYEAR)

bern_data_long2_factored <- bern_data_long2_factored %>% mutate(alter_g=ifelse(alter<30,"<30",
                                                                               ifelse(alter>=30&alter<60,"30-59",
                                                                               ifelse(alter>=60,">60",NA))))

bern_data_long2_factored$alter_g <- as.factor(bern_data_long2_factored$alter_g)

bern_data_long2_factored$alter_g <- fct_relevel(bern_data_long2_factored$alter_g, "<30", "30-59", ">60")

#GENDER--------------------------------

bern_data_long2_factored <-  bern_data_long2_factored %>% mutate(gender=ifelse(SD_GENDER=="Maennlich","male",
                                                                        ifelse(SD_GENDER=="Weiblich","female",NA)))

bern_data_long2_factored$gender <- as.factor(bern_data_long2_factored$gender)

#REGION--------------------------------

bern_data_long2_factored$bula = as.factor(droplevels(bern_data_long2_factored$SD_BULA))
bern_data_long2_factored$bula = bern_data_long2_factored$bula %>% fct_relevel(., sort)
levels(bern_data_long2_factored$bula)<-c("BG","KT","NÖ","OÖ","SB","ST","TI","VB","WI")

#INCOME--------------------------------

bern_data_long2_factored <- bern_data_long2_factored %>% mutate( 
  hh_inc_cur_quintile= ifelse(hh_inc_cur=="weniger als 1.100 Euro" | hh_inc_cur=="1.100 bis unter 1.500 Euro", "1.Quintile",
                   ifelse(hh_inc_cur=="1.500 bis unter 1.800 Euro" | hh_inc_cur=="1.800 bis unter 2.200 Euro", "2.Quintile", 
                   ifelse(hh_inc_cur=="2.200 bis unter 2.700 Euro" | hh_inc_cur=="2.700 bis unter 3.100 Euro", "3.Quintile" ,
                   ifelse(hh_inc_cur=="3.100 bis unter 3.700 Euro" | hh_inc_cur=="3.700 bis unter 4.300 Euro", "4.Quintile", 
                   ifelse(hh_inc_cur=="4.300 bis unter 5.500 Euro" | hh_inc_cur=="5.500 Euro und mehr"       , "5.Quintile",NA))))))


bern_data_long2_factored <- bern_data_long2_factored %>% mutate( 
  hh_inc_cur_3g  = ifelse(hh_inc_cur=="weniger als 1.100 Euro"     | hh_inc_cur=="1.100 bis unter 1.500 Euro" | hh_inc_cur=="1.500 bis unter 1.800 Euro" , "1-3.Decile",
                   ifelse(hh_inc_cur=="1.800 bis unter 2.200 Euro" | hh_inc_cur=="2.200 bis unter 2.700 Euro" | hh_inc_cur=="2.700 bis unter 3.100 Euro" 
                        | hh_inc_cur=="3.100 bis unter 3.700 Euro", "4-7.Decile",
                   ifelse(hh_inc_cur=="3.700 bis unter 4.300 Euro" | hh_inc_cur=="4.300 bis unter 5.500 Euro" | hh_inc_cur=="5.500 Euro und mehr"       , "8-10.Decile",NA))))

#POPULATION---------------------------

bern_data_long2_factored <- bern_data_long2_factored %>% mutate( 
  population_3g  = ifelse(SD_POPNUM=="<2.500"  | SD_POPNUM=="2.500-" | SD_POPNUM=="5.000-" , "<10.000",
                   ifelse(SD_POPNUM=="10.000-" | SD_POPNUM=="50.000-", "10.000–1 Million",
                   ifelse(SD_POPNUM=="1M.+", ">1 Million",NA))))

bern_data_long2_factored$population_3g <- as.factor(bern_data_long2_factored$population_3g)
bern_data_long2_factored$population_3g <- fct_relevel(bern_data_long2_factored$population_3g, "<10.000","10.000–1 Million",">1 Million")

#EMPLOYMENT STATUS-------------------

#wave1
# *(self) employed as usal
bern_data_long2_factored <- bern_data_long2_factored %>% mutate(empl=ifelse(as.numeric(SD_EMPLSTATUS_FEB2020) < 4 & (as.numeric(berufa_kaen) == 2 | as.numeric(berufa_kang) == 2) & (Paneli_W1 == 1	& wave == 1),"(self) employed as usual",NA))
bern_data_long2_factored <- bern_data_long2_factored %>% mutate(empl=ifelse(as.numeric(SD_EMPLSTATUS_FEB2020) < 4 & (as.numeric(berufa_urla) == 2 | as.numeric(berufa_aufs) == 2) & (Paneli_W1 == 1	& wave == 1),"(self) employed as usual",empl))
bern_data_long2_factored <- bern_data_long2_factored %>% mutate(empl=ifelse(as.numeric(SD_EMPLSTATUS_FEB2020) < 4 & (as.numeric(berufa_awsk) == 2 | as.numeric(berufa_hafo) == 2) & (Paneli_W1 == 1	& wave == 1),"(self) employed as usual",empl))

#	*furlough
bern_data_long2_factored <- bern_data_long2_factored %>% mutate(empl=ifelse(as.numeric(SD_EMPLSTATUS_FEB2020) < 4 & as.numeric(berufa_kurz) == 2 & (Paneli_W1 == 1	& wave == 1),"furlough",empl))

#	*home office
bern_data_long2_factored <- bern_data_long2_factored %>% mutate(empl=ifelse(as.numeric(SD_EMPLSTATUS_FEB2020) < 4 & as.numeric(berufa_home) == 2 & (Paneli_W1 == 1	& wave == 1),"home office",empl))

#	*unemployed
bern_data_long2_factored <- bern_data_long2_factored %>% mutate(empl=ifelse(as.numeric(SD_EMPLSTATUS_FEB2020) == 4 & (Paneli_W1 == 1 & wave == 1),"unemployed",empl))
bern_data_long2_factored <- bern_data_long2_factored %>% mutate(empl=ifelse((as.numeric(berufa_kuen) %in% 2 | as.numeric(berufa_arbu) %in% 2 | as.numeric(berufa_sozh) %in% 2 | as.numeric(berufa_kasa) %in% 2) & (Paneli_W1 %in% 1 & wave %in% 1),"unemployed",empl))

# *not in labour market
bern_data_long2_factored <- bern_data_long2_factored %>% mutate(empl=ifelse(as.numeric(SD_EMPLSTATUS_FEB2020) > 4 & as.numeric(SD_EMPLSTATUS_FEB2020) < 11 & (Paneli_W1 == 1	& wave == 1),"not in labour market",empl))

#!wave1
bern_data_long2_factored <- bern_data_long2_factored %>% mutate(panelist2=ifelse(Paneli_W1 == 1 & wave==1,1,
                                                ifelse(Paneli_W2 == 1 & wave==2,2,
                                                ifelse(Paneli_W3 == 1 & wave==3,3,
                                                ifelse(Paneli_W4 == 1 & wave==4,4,
                                                ifelse(Paneli_W5 == 1 & wave==5,5,
                                                ifelse(Paneli_W6 == 1 & wave==6,6,
                                                ifelse(Paneli_W7 == 1 & wave==7,7,
                                                ifelse(Paneli_W8 == 1 & wave==8,8,
                                                ifelse(Paneli_W9 == 1 & wave==9,9,
                                                ifelse(Paneli_W10 == 1 & wave==10,10,
                                                ifelse(Paneli_W11 == 1 & wave==11,11,
                                                ifelse(Paneli_W12 == 1 & wave==12,12,
                                                ifelse(Paneli_W13 == 1 & wave==13,13,
                                                ifelse(Paneli_W14 == 1 & wave==14,14,
                                                ifelse(Paneli_W15 == 1 & wave==15,15,
                                                ifelse(Paneli_W16 == 1 & wave==16,16,
                                                ifelse(Paneli_W17 == 1 & wave==17,17,
                                                ifelse(Paneli_W18 == 1 & wave==18,18,
                                                ifelse(Paneli_W19 == 1 & wave==19,19,
                                                ifelse(Paneli_W20 == 1 & wave==20,20,
                                                ifelse(Paneli_W21 == 1 & wave==21,21,
                                                ifelse(Paneli_W22 == 1 & wave==22,22,
                                                ifelse(Paneli_W23 == 1 & wave==23,23,
                                                ifelse(Paneli_W24 == 1 & wave==24,24,
                                                ifelse(Paneli_W25 == 1 & wave==25,25,
                                                ifelse(Paneli_W26 == 1 & wave==26,26,
                                                ifelse(Paneli_W27 == 1 & wave==27,27,
                                                ifelse(Paneli_W28 == 1 & wave==28,28,
                                                ifelse(Paneli_W29 == 1 & wave==29,29,
                                                ifelse(Paneli_W30 == 1 & wave==30,30,
                                                ifelse(Paneli_W31 == 1 & wave==31,31,
                                                ifelse(Paneli_W32 == 1 & wave==32,32,
                                                ifelse(Paneli_W33 == 1 & wave==33,33,NA))))))))))))))))))))))))))))))))))

bern_data_long2_factored <- bern_data_long2_factored %>% mutate(empl=ifelse(as.numeric(berufst) < 4 & (panelist2>1),"(self) employed as usual",empl))

bern_data_long2_factored <- bern_data_long2_factored %>% mutate(empl=ifelse((as.numeric(berufa_kurz) %in% 2) & (panelist2>1),"furlough",empl))

bern_data_long2_factored <- bern_data_long2_factored %>% mutate(empl=ifelse((as.numeric(berufa_home) %in% 2) & (panelist2>1),"home office",empl))

bern_data_long2_factored <- bern_data_long2_factored %>% mutate(empl=ifelse((as.numeric(berufst) == 4|as.numeric(berufa_kasa) %in% 2 | as.numeric(berufa_sozh) %in% 2 | as.numeric(berufa_arbu) %in% 2 | as.numeric(berufa_kuen) %in% 2) & (panelist2>1),"unemployed",empl))

bern_data_long2_factored <- bern_data_long2_factored %>% mutate(empl=ifelse(((as.numeric(berufst) > 4)&(as.numeric(berufst) < 11)) & (panelist2>1),"not in labour market",empl))

#table(bern_data_long2_factored$empl)

bern_data_long2_factored$empl<-as.factor(bern_data_long2_factored$empl)
levels(bern_data_long2_factored$empl)<-c("Arbeitend","in Kurzarbeit","in Home-office","Nicht-Arbeitend","Arbeitslos")
bern_data_long2_factored$empl <- fct_relevel(bern_data_long2_factored$empl, "Arbeitend","in Kurzarbeit","in Home-office","Arbeitslos","Nicht-Arbeitend")


```

```{r recoding and export, echo=FALSE, fig.width=8, fig.height=5, results='asis'}

#change avoiding answer in satisfaction question to NA
bern_data_long2_factored$zuf_fam[bern_data_long2_factored$zuf_fam=="trifft nicht zu (keine Familie/ Partner/in/ nicht berufstaetig)"]<-NA
bern_data_long2_factored$zuf_par[bern_data_long2_factored$zuf_par=="trifft nicht zu (keine Familie/ Partner/in/ nicht berufstaetig)"]<-NA
bern_data_long2_factored$zuf_ber[bern_data_long2_factored$zuf_ber=="trifft nicht zu (keine Familie/ Partner/in/ nicht berufstaetig)"]<-NA
bern_data_long2_factored$zuf_frz[bern_data_long2_factored$zuf_frz=="trifft nicht zu (keine Familie/ Partner/in/ nicht berufstaetig)"]<-NA

bern_data_long2_factored$zuf_fam<-droplevels(bern_data_long2_factored$zuf_fam)
bern_data_long2_factored$zuf_par<-droplevels(bern_data_long2_factored$zuf_par)
bern_data_long2_factored$zuf_ber<-droplevels(bern_data_long2_factored$zuf_ber)
bern_data_long2_factored$zuf_frz<-droplevels(bern_data_long2_factored$zuf_frz)

lr_gen_w1 <- bern_data_long2_factored %>% filter(!is.na(WEIGHTD))

#List of all variables in the data
#names(lr_gen_w1)
#paste(names(lr_gen_w1),collapse=",")

#What variables should be used for the dashboard 
 variablelist <- c("ges_per_gefahr","ges_pub_gefahr","wir_per_gefahr","wir_pub_gefahr",
                   "wochentag","kontakt","zeit" ,"konflikt","kinder",
                   "depress_A1","depress_A2","depress_A3","depress_A4",
                   "depress_A5","depress_A6","depress_A7","depress_A8","depress_A9",
                   "zusammenhalt","umweundklima","onlinekommun",
                   "demokratie","lebensz",
                   "zus_bestes","zus_einig","zus_schutzen",
                   "blianz_reg",
                   "zuf_reg_al","zuf_reg_un","zuf_reg_wi",
                   "mas_angemessen","mas_effektiv",
                   "ver_gov","ver_ges","ver_par","ver_pol","ver_orf",
                   "dauer",
                   "fin_ausk_akt","fin_ausk_yea","eco_ausk_yea",
                   "zuf_fam","zuf_par","zuf_ber","zuf_frz",
                   "skept_lebens","skept_wichti","skept_behaup","skept_andere",
                   "skept_fehler","skept_uebert","skept_grippe","skept_gerech",
                   "tax_gleich","tax_ineq","tax_hurt","tax_quarant",
                   "kaufen_haus",
                   "zeitp_spar","zeitp_inve","zeitp_lieg","zeitp_ausg","zeitp_kred",
                   "anst_rest","anst_oeff","anst_arbe","anst_schu","anst_park",
                   "anst_arzt","anst_fami","anst_freu",
                   "mastest_eff","mastest_zuv","mastest_tre","mastest_str","mastest_mot",
                   "impf_pfl","impf_gra","impf_pfb","impf_kin","impf_soz", 
                   "issue_ungl","issue_faul","issue_albe","issue_wirt",
                   "issue_frau","issue_poli","issue_zuwa","issue_umwe",
                   "issue_eink","issue_gena","issue_redu",
                   "welfshov_such","welfshov_zust","welfshov_sozl",
                   "sozkont",
                   "sozialn_verh_eig_abs","sozialn_verh_eig_hau",
                   "sozialn_verh_eig_sch","sozialn_verh_eig_ver"
)

#variablelist <- c("ges_per_gefahr","ges_pub_gefahr","wochentag","kontakt","lebensz")

#What are the crucial values to identify individual datapoints and what are the categories for subgroup analyses
sociodem <-c("WEIGHTD","id","wave","wavedate","gender","alter_g","edu4","population_3g","hh_inc_cur_3g","empl")

#Get the different factor scales in the data and generate a dataframe indicating which variables use different answer scales
labels <- lr_gen_w1 %>% ungroup() %>% select(variablelist) %>%  sapply(levels)

df <- do.call(rbind, labels) %>% as.data.frame()
df <-bind_rows(lapply(labels,function(y) as.data.frame(t(y),stringsAsFactors=FALSE,y.id = "column_label")))
rownames(df)<-names(labels)

grouped_labels<- df %>% 
  mutate(variable=rownames(.)) %>%
  group_by(V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13) %>% 
  mutate(ID = group_indices()) 


#hinzufügen von nummerierung in labels ohne nummerierung
df2<-df

df2<-df2%>%mutate(V1 = ifelse(!is.na(df$V1) & df$V1!="Weiss nicht" & df$V1!="keine Angabe" & grepl("^[^0-9]",df$V1),
                              paste0("0 = ", df$V1),
                               ifelse(!is.na(df$V1),V1,NA)))
df2<-df2%>%mutate(V2 = ifelse(!is.na(df$V2) & df$V2!="Weiss nicht" & df$V2!="keine Angabe" & grepl("^[^0-9]",df$V2),
                              paste0("1 = ", df$V2),
                               ifelse(!is.na(df$V2),V2,NA)))
df2<-df2%>%mutate(V3 = ifelse(!is.na(df$V3) & df$V3!="Weiss nicht" & df$V3!="keine Angabe" & grepl("^[^0-9]",df$V3),
                              paste0("2 = ", df$V3),
                               ifelse(!is.na(df$V3),V3,NA)))
df2<-df2%>%mutate(V4 = ifelse(!is.na(df$V4) & df$V4!="Weiss nicht" & df$V4!="keine Angabe" & grepl("^[^0-9]",df$V4),
                              paste0("3 = ", df$V4),
                               ifelse(!is.na(df$V4),V4,NA)))
df2<-df2%>%mutate(V5 = ifelse(!is.na(df$V5) & df$V5!="Weiss nicht" & df$V5!="keine Angabe" & grepl("^[^0-9]",df$V5),
                              paste0("4 = ", df$V5),
                               ifelse(!is.na(df$V5),V5,NA)))
df2<-df2%>%mutate(V6 = ifelse(!is.na(df$V6) & df$V6!="Weiss nicht" & df$V6!="keine Angabe" & grepl("^[^0-9]",df$V6),
                              paste0("5 = ", df$V6),
                               ifelse(!is.na(df$V6),V6,NA)))
df2<-df2%>%mutate(V7 = ifelse(!is.na(df$V7) & df$V7!="Weiss nicht" & df$V7!="keine Angabe" & grepl("^[^0-9]",df$V7),
                              paste0("6 = ", df$V7),
                               ifelse(!is.na(df$V7),V7,NA)))
df2<-df2%>%mutate(V8 = ifelse(!is.na(df$V8) & df$V8!="Weiss nicht" & df$V8!="keine Angabe" & grepl("^[^0-9]",df$V8),
                              paste0("7 = ", df$V8),
                               ifelse(!is.na(df$V8),V8,NA)))
df2<-df2%>%mutate(V9 = ifelse(!is.na(df$V9) & df$V9!="Weiss nicht" & df$V9!="keine Angabe" & grepl("^[^0-9]",df$V9),
                              paste0("8 = ", df$V9),
                               ifelse(!is.na(df$V9),V9,NA)))
df2<-df2%>%mutate(V10 = ifelse(!is.na(df$V10) & df$V10!="Weiss nicht" & df$V10!="keine Angabe" & grepl("^[^0-9]",df$V10),
                               paste0("9 = ", df$V10),
                               ifelse(!is.na(df$V10),V10,NA)))
df2<-df2%>%mutate(V11 = ifelse(!is.na(df$V11) & df$V11!="Weiss nicht" & df$V11!="keine Angabe" & grepl("^[^0-9]",df$V11),
                               paste0("10 = ", df$V11),
                               ifelse(!is.na(df$V11),V11,NA)))
df2<-df2%>%mutate(V12 = ifelse(!is.na(df$V12) & df$V12!="Weiss nicht" & df$V12!="keine Angabe" & grepl("^[^0-9]",df$V12),
                               paste0("11 = ", df$V12),
                               ifelse(!is.na(df$V12),V12,NA)))
df2<-df2%>%mutate(V13 = ifelse(!is.na(df$V13) & df$V13!="Weiss nicht" & df$V13!="keine Angabe" & grepl("^[^0-9]",df$V13),
                               paste0("12 = ", df$V13),
                               ifelse(!is.na(df$V13),V13,NA)))

df2<-df2 %>% mutate(variable=rownames(.))

df2$V5[df2$V5=="4 = Mehr als 6 Monate"]<-"7 = Mehr als 6 Monate"


for (val in df2$variable) {
  #print(val)
  test<-df2%>%filter(variable==val)%>%select(starts_with("V", ignore.case=FALSE))
  levels(lr_gen_w1[[val]])<-as.vector(t(test[colSums(!is.na(test)) > 0]))
}

 

grouped_labels<-grouped_labels%>% group_by(ID) %>% summarise(variable)

grouped_labels<- grouped_labels %>% left_join(rev_labels, by = "variable")

#select the data for analyses
lr_gen_w2 <- lr_gen_w1 %>% select(c(variablelist,sociodem))

#group the data into different dataframes within a list according to their answer scales
count=0
out <- vector('list', max(unique(grouped_labels$ID)))
for (val in unique(grouped_labels$ID)) {
count = count+1
out[[count]] <- gather(lr_gen_w2, variable, measurement, grouped_labels%>%filter(ID==count)%>%ungroup()%>%pull(variable), factor_key=TRUE) %>%
  select(id,wave,WEIGHTD,wavedate,gender,alter_g,edu4,population_3g,hh_inc_cur_3g,empl,variable,measurement)
out[[count]]$measurement<-as.factor(out[[count]]$measurement)
out[[count]]$measurement=fct_relevel(out[[count]]$measurement,levels(lr_gen_w2[[(grouped_labels%>%filter(ID==count)%>%ungroup()%>%pull(variable))[1]]]))

#out[[count]] <- pivot_longer(lr_gen_w2,grouped_labels%>%filter(ID==count)%>%ungroup()%>%pull(variable), names_to = "variable", values_to = "measurement") 
#out[[count]] <- gather(lr_gen_w2, variable, measurement, grouped_labels%>%filter(ID==count)%>%ungroup()%>%pull(variable), factor_key=FALSE) #%>%
  #select(id,wave,WEIGHTD,wavedate,gender,alter_g,edu4,population_3g,hh_inc_cur_3g,variable,measurement)
print(count)
}

#calculate N and shares of variables by wave and variable within each specific scale specific dataframe 
data_plot_long_N<- vector('list', max(unique(grouped_labels$ID)))
data_plot_long<- vector('list', max(unique(grouped_labels$ID)))
for (val in unique(grouped_labels$ID)) {
data_plot_long_N[[val]]<-out[[val]] %>% filter(!is.na(measurement)) %>% 
 group_by(wavedate,variable) %>% tally() %>% rename(N_total=n)

data_plot_long[[val]]<-out[[val]] %>% filter(!is.na(measurement)) %>%
  as_survey_design(weights = c(WEIGHTD)) %>%
  group_by(wavedate,variable,measurement) %>% 
  summarise(n=survey_total(vartype = c("se")))

data_plot_long[[val]]<-data_plot_long[[val]] %>% group_by(wavedate,variable) %>%
     mutate(prop = n/sum(n),ymax=prop+1.96*sqrt(n/sum(n))*(1-(n/sum(n)))/n, ymin=prop-1.96*sqrt(n/sum(n))*(1-(n/sum(n)))/n,groupby="none")
print(val)
}

#append it and add new variable with levels of measurement as content indicating different scales
data_plot_long_new<-bind_rows(data_plot_long, .id = 'scales')
data_plot_long_N_new<-bind_rows(data_plot_long_N, .id = 'scales')

#Remove "Number = " in labels of measurement
#data_plot_long_new<-data_plot_long_new %>% mutate(measurement=gsub("^.*?= ","",measurement))

#MEAN VALUES#################################################################
#out

#mean line attention recoding 5= sehr groß 1= sehr klein

data_plot_long_mean<- vector('list', max(unique(grouped_labels$ID)))
data_plot_long_mean_ge<- vector('list', max(unique(grouped_labels$ID)))
data_plot_long_mean_ag<- vector('list', max(unique(grouped_labels$ID)))
data_plot_long_mean_ed<- vector('list', max(unique(grouped_labels$ID)))
data_plot_long_mean_bl<- vector('list', max(unique(grouped_labels$ID)))
data_plot_long_mean_hi<- vector('list', max(unique(grouped_labels$ID)))
data_plot_long_mean_es<- vector('list', max(unique(grouped_labels$ID)))

grouped_labels_sum <- grouped_labels %>% group_by(ID) %>% filter(row_number()==1)

#test

# data_plot_long_mean[[3]] <- out[[3]]  %>% filter(!is.na(measurement)) %>%
#   as_survey_design(weights = c(WEIGHTD)) %>%
#   group_by(wavedate,variable,hh_inc_cur_3g) %>%
#   summarise(mean_measurement=survey_mean(abs((as.numeric(measurement)-grouped_labels_sum$min[grouped_labels_sum$ID==3])+((grouped_labels_sum$max[grouped_labels_sum$ID==3]-grouped_labels_sum$min[grouped_labels_sum$ID==3])*(-grouped_labels_sum$rev[grouped_labels_sum$ID==3]))),vartype = c("se")),
#             #mean_tot1 = survey_total(measurement),
#             #mean_tot2 = survey_total(!is.na(measurement)),
#             mean_tot3 = n()) %>%
#   group_by(wavedate,variable,hh_inc_cur_3g) %>%
#      mutate(ymax=mean_measurement+1.96*mean_measurement_se, ymin=mean_measurement-1.96*mean_measurement_se,groupby="all",subgroup="hi")

#endtest

for (val in unique(grouped_labels$ID)) {
#mean general
  print("start")
  print(val)
data_plot_long_mean[[val]] <- out[[val]]  %>% filter(!is.na(measurement)) %>%
  as_survey_design(weights = c(WEIGHTD)) %>%
  group_by(wavedate,variable) %>%
  summarise(mean_measurement=survey_mean(abs((as.numeric(as.factor(measurement))-grouped_labels_sum$min[val])+((grouped_labels_sum$max[val]-grouped_labels$min[val])*(-grouped_labels_sum$rev[val]))),vartype = c("se")),
            mean_tot = n()) %>% 
  group_by(wavedate,variable) %>%
     mutate(ymax=mean_measurement+1.96*mean_measurement_se, ymin=mean_measurement-1.96*mean_measurement_se,groupby="all",subgroup="none")


#mean by Gender
data_plot_long_mean_ge[[val]] <- out[[val]]  %>% filter(!is.na(measurement)&!is.na(gender)) %>%
  as_survey_design(weights = c(WEIGHTD)) %>%
  group_by(wavedate,variable,gender) %>%
 summarise(mean_measurement=survey_mean(abs((as.numeric(as.factor(measurement))-grouped_labels_sum$min[val])+((grouped_labels_sum$max[val]-grouped_labels_sum$min[val])*(-grouped_labels_sum$rev[val]))),vartype = c("se")),
            mean_tot = n()) %>%  
  group_by(wavedate,variable,gender) %>%
     mutate(ymax=mean_measurement+1.96*mean_measurement_se, ymin=mean_measurement-1.96*mean_measurement_se,groupby="ge")

#mean by Age
data_plot_long_mean_ag[[val]] <- out[[val]]  %>% filter(!is.na(measurement)&!is.na(alter_g)) %>%
  as_survey_design(weights = c(WEIGHTD)) %>%
  group_by(wavedate,variable,alter_g) %>%
  summarise(mean_measurement=survey_mean(abs((as.numeric(as.factor(measurement))-grouped_labels_sum$min[val])+((grouped_labels_sum$max[val]-grouped_labels_sum$min[val])*(-grouped_labels_sum$rev[val]))),vartype = c("se")),
            mean_tot = n()) %>%  
  group_by(wavedate,variable,alter_g) %>%
     mutate(ymax=mean_measurement+1.96*mean_measurement_se, ymin=mean_measurement-1.96*mean_measurement_se,groupby="ag")

#mean by Education
data_plot_long_mean_ed[[val]] <- out[[val]]  %>% filter(!is.na(measurement)&!is.na(edu4)) %>%
  as_survey_design(weights = c(WEIGHTD)) %>%
  group_by(wavedate,variable,edu4) %>%
  summarise(mean_measurement=survey_mean(abs((as.numeric(as.factor(measurement))-grouped_labels_sum$min[val])+((grouped_labels_sum$max[val]-grouped_labels_sum$min[val])*(-grouped_labels_sum$rev[val]))),vartype = c("se")),
            mean_tot = n()) %>%  
  group_by(wavedate,variable,edu4) %>%
     mutate(ymax=mean_measurement+1.96*mean_measurement_se, ymin=mean_measurement-1.96*mean_measurement_se,groupby="ed")

#mean by size of home municipality
data_plot_long_mean_bl[[val]] <- out[[val]]  %>% filter(!is.na(measurement)&!is.na(population_3g)) %>%
  as_survey_design(weights = c(WEIGHTD)) %>%
  group_by(wavedate,variable,population_3g) %>%
  summarise(mean_measurement=survey_mean(abs((as.numeric(as.factor(measurement))-grouped_labels_sum$min[val])+((grouped_labels_sum$max[val]-grouped_labels_sum$min[val])*(-grouped_labels_sum$rev[val]))),vartype = c("se")),
            mean_tot = n()) %>%  
  group_by(wavedate,variable,population_3g) %>%
     mutate(ymax=mean_measurement+1.96*mean_measurement_se, ymin=mean_measurement-1.96*mean_measurement_se,groupby="bl")

#mean by Household Income
data_plot_long_mean_hi[[val]] <- out[[val]]  %>% filter(!is.na(measurement)&!is.na(hh_inc_cur_3g)) %>%
  as_survey_design(weights = c(WEIGHTD)) %>%
  group_by(wavedate,variable,hh_inc_cur_3g) %>%
  summarise(mean_measurement=survey_mean(abs((as.numeric(as.factor(measurement))-grouped_labels_sum$min[val])+((grouped_labels_sum$max[val]-grouped_labels_sum$min[val])*(-grouped_labels_sum$rev[val]))),vartype = c("se")),
            mean_tot = n()) %>%  
  group_by(wavedate,variable,hh_inc_cur_3g) %>%
     mutate(ymax=mean_measurement+1.96*mean_measurement_se, ymin=mean_measurement-1.96*mean_measurement_se,groupby="hi")

#mean by employment status
data_plot_long_mean_es[[val]] <- out[[val]]  %>% filter(!is.na(measurement)&!is.na(empl)) %>%
  as_survey_design(weights = c(WEIGHTD)) %>%
  group_by(wavedate,variable,empl) %>%
  summarise(mean_measurement=survey_mean(abs((as.numeric(as.factor(measurement))-grouped_labels_sum$min[val])+((grouped_labels_sum$max[val]-grouped_labels_sum$min[val])*(-grouped_labels_sum$rev[val]))),vartype = c("se")),
            mean_tot = n()) %>%  
  group_by(wavedate,variable,empl) %>%
     mutate(ymax=mean_measurement+1.96*mean_measurement_se, ymin=mean_measurement-1.96*mean_measurement_se,groupby="es")

print(val)
print("end")
}

#append it and add new variable with levels of measurement as content indicating different scales
data_plot_long_mean_new<-bind_rows(data_plot_long_mean, .id = 'scales')
data_plot_long_mean_ge_new<-bind_rows(data_plot_long_mean_ge, .id = 'scales')%>%rename("subgroup" = gender)
data_plot_long_mean_ag_new<-bind_rows(data_plot_long_mean_ag, .id = 'scales')%>%rename("subgroup" = alter_g)
data_plot_long_mean_ed_new<-bind_rows(data_plot_long_mean_ed, .id = 'scales')%>%rename("subgroup" = edu4)
data_plot_long_mean_bl_new<-bind_rows(data_plot_long_mean_bl, .id = 'scales')%>%rename("subgroup" = population_3g)
data_plot_long_mean_hi_new<-bind_rows(data_plot_long_mean_hi, .id = 'scales')%>%rename("subgroup" = hh_inc_cur_3g)
data_plot_long_mean_es_new<-bind_rows(data_plot_long_mean_es, .id = 'scales')%>%rename("subgroup" = empl)


export_shiny_data <- bind_rows(data_plot_long_mean_new,
                               data_plot_long_mean_ge_new,
                               data_plot_long_mean_ag_new,
                               data_plot_long_mean_ed_new,
                               data_plot_long_mean_bl_new,
                               data_plot_long_mean_hi_new,
                               data_plot_long_mean_es_new)


#combine shares and N to one dataframe
export_shiny_data <- left_join(export_shiny_data, data_plot_long_N_new,by=c("wavedate"="wavedate","variable"="variable","scales"="scales"))

#Round the data before exporting
export_shiny_data <- export_shiny_data %>% mutate(mean_measurement=round(mean_measurement,2),
                                                  mean_measurement_se=round(mean_measurement_se,2),
                                                  ymax=round(ymax,2),
                                                  ymin=round(ymin,2))

#MERGE LABELING of SCALES TO DATA

grouped_labels<-grouped_labels %>%rename(scales=ID)

#Remove "Number = " in labels of measurement
df<-df %>% mutate_all(~(gsub("^.*?= ","",.)))


grouped_labels2<-df %>%mutate(variable=rownames(.)) %>% left_join(grouped_labels,by = c("variable"))
grouped_labels2 <- grouped_labels2 %>% mutate(na=rowSums(is.na(.)))

grouped_labels2$wn <- apply(df=='Weiss nicht', 1, FUN= function(x) toString(names(na.omit(x))[na.omit(x)]))
grouped_labels2$ka <- apply(df=='keine Angabe', 1, FUN= function(x) toString(names(na.omit(x))[na.omit(x)]))
grouped_labels2$wn[grouped_labels2$wn==""]<-NA
grouped_labels2$ka[grouped_labels2$ka==""]<-NA
grouped_labels2 <- grouped_labels2 %>% mutate(scalenumber=12-na-(!is.na(wn))-(!is.na(ka)))

grouped_labels2$wn[is.na(grouped_labels2$wn)]<-"nown"
grouped_labels2$ka[is.na(grouped_labels2$ka)]<-"noka"
grouped_labels2$nown="no WN option"
grouped_labels2$noka="no KA option"

# count number of discrete values and WN/KA variable #TO DO##########################################

#combine shares and N to one dataframe
export_shiny_data_shares <- left_join(data_plot_long_new, data_plot_long_N_new,by=c("wavedate"="wavedate","variable"="variable","scales"="scales"))

#Round the data before exporting
export_shiny_data_shares <- export_shiny_data_shares %>% select(-c(n,n_se)) %>% mutate(prop=round(prop,3),
                                                                                       ymax=round(ymax,3),
                                                                                       ymin=round(ymin,3))



#data_long$measurement<-as.factor(data_long$measurement)
#levels(data_long$variable) <- c("Ges. Gefahr Persönlich", "Ges. Gefahr Für die österr. Bevölkerung"," Wir. Gefahr Persönlich", "Wir. Gefahr Für die österr. Bevölkerung")

#levels(data_plot_long_mean$variable) <- c("Ges. Gefahr Persönlich", "Ges. Gefahr Für die österr. Bevölkerung"," Wir. Gefahr Persönlich", "Wir. Gefahr Für die österr. Bevölkerung")


```

```{r download and export covid19 cases, echo=FALSE, fig.width=8, fig.height=5, results='asis'}

#Export the data
write_csv(export_shiny_data, "./output/tables/export_shiny_data.csv", na = "NA")
#write.csv(export_shiny_data, "./output/tables/export_shiny_data.csv", na = "NA")
write_csv(export_shiny_data_shares, "./output/tables/export_shiny_data_shares.csv", na = "NA")
write_csv(grouped_labels2, "./output/tables/grouped_labels.csv", na = "NA")


epidf2 =            read.delim("https://covid19-dashboard.ages.at/data/CovidFaelle_Timeline.csv", sep=";", header=TRUE)

write_csv(epidf2, "./output/tables/CovidFaelle_Timeline.csv", na = "NA")

```

## Alternative example with Datawrapper

```{r example data export for gesundheitliche Gefahr, echo=FALSE, fig.width=8, fig.height=5, results='asis',include=FALSE}
#GESUNDHEITLICH#########################

lr_gen_w1 <- bern_data_long2_factored %>% filter(!is.na(WEIGHTD))

data_long <- gather(lr_gen_w1, condition, measurement, ges_per_gefahr:ges_pub_gefahr, factor_key=TRUE)
data_long$measurement<-as.factor(data_long$measurement)

data_plot_long_N<-data_long %>% filter(!is.na(measurement)) %>% 
 group_by(wave,condition) %>% tally()

data_plot_long<-data_long %>% filter(!is.na(measurement)) %>%
  as_survey_design(weights = c(WEIGHTD)) %>%
  group_by(wave,condition,measurement) %>% 
  summarise(n=survey_total(vartype = c("se")))

data_plot_long<-data_plot_long %>% group_by(wave,condition) %>%
     mutate(prop = n/sum(n),ymax=prop+1.96*sqrt(n/sum(n))*(1-(n/sum(n)))/n, ymin=prop-1.96*sqrt(n/sum(n))*(1-(n/sum(n)))/n)

data_plot_long$wave<-as.factor(data_plot_long$wave)
levels(data_plot_long$wave) <-c("W1", "W2", "W3","W4","W5","W6","W7","W8","W9","W10","W11","W12","W13","W14","W15","W16","W17","W18","W19","W20","W21","W22","W23","W24")
levels(data_plot_long$condition) <- c("Persönlich", "Für die österr. Bevölkerung")
levels(data_plot_long$measurement) <- c("sehr groß", "groß", "mittelmäßig", "klein", "sehr klein")

data_plot_long$measurement <- fct_relevel(data_plot_long$measurement, "sehr klein", "klein", "mittelmäßig", "groß", "sehr groß")

#mean line attention recoding 5= sehr groß 1= sehr klein
data_plot_long_mean <- data_long  %>% filter(!is.na(measurement)) %>%
  as_survey_design(weights = c(WEIGHTD)) %>%
  group_by(wavedate,condition) %>%
  summarise(mean_measurement=survey_mean(6-as.numeric(measurement),vartype = c("se"))) %>% group_by(wavedate,condition) %>%
     mutate(ymax=mean_measurement+1.96*mean_measurement_se, ymin=mean_measurement-1.96*mean_measurement_se)

levels(data_plot_long_mean$condition) <- c("Persönlich", "Für die österr. Bevölkerung")

data_plot_long_mean_export <- data_plot_long_mean %>% 
  select(-c(mean_measurement_se)) %>%
  pivot_wider(id_cols = c(wavedate,condition),names_from=condition, values_from=c(mean_measurement,ymax,ymin), names_glue = "{condition}_{.value}")

data_plot_long_mean_export_rn <- data_plot_long_mean_export %>% ungroup() %>%
  rename("Persönlich"='Persönlich_mean_measurement',
         "Für die österr. Bevölkerung"='Für die österr. Bevölkerung_mean_measurement')

write_csv(data_plot_long%>%filter(condition=="Für die österr. Bevölkerung"), "./output/tables/figure1_shares.csv", na = "NA")
write_csv(data_plot_long_mean_export_rn, "./output/tables/figure1_mean.csv", na = "NA")
write_csv(data_plot_long_N, "./output/tables/figure1_observations.csv", na = "NA")
```

# add q_text and q_cate to each variable
```{r pressure, echo=FALSE}

data_labels <-readr::read_csv("https://raw.githubusercontent.com/fabiankal/woco/master/output/tables/grouped_labels.csv",show_col_types = FALSE)

data_labels$q_text=NA #Question wording
data_labels$q_cate=NA #Question category
data_labels$q_filt=NA #Question filter

# Gefahrenwahrnehmung
data_labels <- data_labels %>% mutate(q_text=ifelse(variable=="ges_per_gefahr","Wie groß schätzen Sie die gesundheitliche Gefahr ein, welche von dem Coronavirus für Sie persönlich ausgeht?",q_text),
                                      q_text=ifelse(variable=="ges_pub_gefahr","Wie groß schätzen Sie die gesundheitliche Gefahr ein, welche von dem Coronavirus für die österreichische Bevölkerung ausgeht?",q_text),
                                      q_text=ifelse(variable=="wir_per_gefahr","Wie groß schätzen Sie die wirtschaftliche Gefahr ein, welche von dem Coronavirus für die österreichische Bevölkerung ausgeht?",q_text),
                                      q_text=ifelse(variable=="wir_pub_gefahr","Wie groß schätzen Sie die wirtschaftliche Gefahr ein, welche von dem Coronavirus für die österreichische Bevölkerung ausgeht?",q_text),
                                                                            
                                      q_cate=ifelse(variable=="ges_per_gefahr","Gefahrenwahrnehmung",q_cate),
                                      q_cate=ifelse(variable=="ges_pub_gefahr","Gefahrenwahrnehmung",q_cate),
                                      q_cate=ifelse(variable=="wir_per_gefahr","Gefahrenwahrnehmung",q_cate),
                                      q_cate=ifelse(variable=="wir_pub_gefahr","Gefahrenwahrnehmung",q_cate),
                                      
                                      q_filt=ifelse(variable=="ges_per_gefahr","no",q_filt),
                                      q_filt=ifelse(variable=="ges_pub_gefahr","no",q_filt),
                                      q_filt=ifelse(variable=="wir_per_gefahr","no",q_filt),
                                      q_filt=ifelse(variable=="wir_pub_gefahr","no",q_filt)
                                      )




# Auswirkungen
data_labels <- data_labels %>% mutate(q_text=ifelse(variable=="wochentag","Wie stark trifft folgende Aussage auf Ihre Erfahrungen in der letzten Woche zu?	Ich vergesse manchmal, welcher Wochentag ist.",q_text),
                                      q_text=ifelse(variable=="kontakt","Wie stark trifft folgende Aussage auf Ihre Erfahrungen in der letzten Woche zu? Mir fehlt der Kontakt zu anderen Menschen.",q_text),
                                      q_text=ifelse(variable=="zeit","Wie stark trifft folgende Aussage auf Ihre Erfahrungen in der letzten Woche zu? Ich kann Dinge tun, für die ich sonst keine Zeit habe.",q_text),
                                      q_text=ifelse(variable=="konflikt","Wie stark trifft folgende Aussage auf Ihre Erfahrungen in der letzten Woche zu? Ich habe mehr Konflikte in meiner Beziehung / Familie. ",q_text),
                                      q_text=ifelse(variable=="kinder","Wie stark trifft folgende Aussage auf Ihre Erfahrungen in der letzten Woche zu? Die Kinderbetreuung stellt ein Problem für mich dar.",q_text),
                                                                            
                                      q_cate=ifelse(variable=="wochentag","Auswirkungen",q_cate),
                                      q_cate=ifelse(variable=="kontakt","Auswirkungen",q_cate),
                                      q_cate=ifelse(variable=="zeit","Auswirkungen",q_cate),
                                      q_cate=ifelse(variable=="konflikt","Auswirkungen",q_cate),
                                      q_cate=ifelse(variable=="kinder","Auswirkungen",q_cate),
                                      
                                      q_filt=ifelse(variable=="wochentag","no",q_filt),
                                      q_filt=ifelse(variable=="kontakt","no",q_filt),
                                      q_filt=ifelse(variable=="zeit","no",q_filt),
                                      q_filt=ifelse(variable=="konflikt","no",q_filt),
                                      q_filt=ifelse(variable=="kinder","Kinder <=14j.=ja",q_filt)
                                      )



# Emotionen
data_labels <- data_labels %>% mutate(q_text=ifelse(variable=="depress_A1","Wie oft waren Sie in der letzten Woche ruhig und gelassen?",q_text),
                                      q_text=ifelse(variable=="depress_A2","Wie oft waren Sie in der letzten Woche einsam?",q_text),
                                      q_text=ifelse(variable=="depress_A3","Wie oft waren Sie in der letzten Woche ärgerlich?",q_text),
                                      q_text=ifelse(variable=="depress_A4","Wie oft waren Sie in der letzten Woche so niedergeschlagen, dass Sie nichts aufheitern konnte?",q_text),
                                      q_text=ifelse(variable=="depress_A5","Wie oft waren Sie in der letzten Woche glücklich?",q_text),
                                      q_text=ifelse(variable=="depress_A6","Wie oft waren Sie in der letzten Woche nervös?",q_text),
                                      q_text=ifelse(variable=="depress_A7","Wie oft waren Sie in der letzten Woche ängstlich?",q_text),
                                      q_text=ifelse(variable=="depress_A8","Wie oft waren Sie in der letzten Woche bedrückt und traurig?",q_text),
                                      q_text=ifelse(variable=="depress_A9","Wie oft waren Sie in der letzten Woche voller Energie?",q_text),
                        
                                                                            
                                      q_cate=ifelse(variable=="depress_A1","Emotionen",q_cate),
                                      q_cate=ifelse(variable=="depress_A2","Emotionen",q_cate),
                                      q_cate=ifelse(variable=="depress_A3","Emotionen",q_cate),
                                      q_cate=ifelse(variable=="depress_A4","Emotionen",q_cate),
                                      q_cate=ifelse(variable=="depress_A5","Emotionen",q_cate),
                                      q_cate=ifelse(variable=="depress_A6","Emotionen",q_cate),
                                      q_cate=ifelse(variable=="depress_A7","Emotionen",q_cate),
                                      q_cate=ifelse(variable=="depress_A8","Emotionen",q_cate),
                                      q_cate=ifelse(variable=="depress_A9","Emotionen",q_cate),
                                      
                                      q_filt=ifelse(variable=="depress_A1","no",q_filt),
                                      q_filt=ifelse(variable=="depress_A2","no",q_filt),
                                      q_filt=ifelse(variable=="depress_A3","no",q_filt),
                                      q_filt=ifelse(variable=="depress_A4","no",q_filt),
                                      q_filt=ifelse(variable=="depress_A5","no",q_filt),
                                      q_filt=ifelse(variable=="depress_A6","no",q_filt),
                                      q_filt=ifelse(variable=="depress_A7","no",q_filt),
                                      q_filt=ifelse(variable=="depress_A8","no",q_filt),
                                      q_filt=ifelse(variable=="depress_A9","no",q_filt)
                                      )



# Chancenwahrnehmung
data_labels <- data_labels %>% mutate(q_text=ifelse(variable=="zusammenhalt","Wie sehr trifft die folgende Aussage aus Ihrer Sicht zu? Der Zusammenhalt in der Gesellschaft hat sich in der letzten Woche erhöht.",q_text),
                                      q_text=ifelse(variable=="umweundklima","Wie sehr trifft die folgende Aussage aus Ihrer Sicht zu? ie Corona-Krise birgt auch Chancen - z.B. für Umwelt und Klima.",q_text),
                                      q_text=ifelse(variable=="onlinekommun","Wie sehr trifft die folgende Aussage aus Ihrer Sicht zu? Die rasche Umstellung auf Online-Kommunikation bringt die Wirtschaft voran.",q_text),
                                                                            
                                      q_cate=ifelse(variable=="zusammenhalt","Chancenwahrnehmung",q_cate),
                                      q_cate=ifelse(variable=="umweundklima","Chancenwahrnehmung",q_cate),
                                      q_cate=ifelse(variable=="onlinekommun","Chancenwahrnehmung",q_cate),
                                      
                                      q_filt=ifelse(variable=="zusammenhalt","no",q_filt),
                                      q_filt=ifelse(variable=="umweundklima","no",q_filt),
                                      q_filt=ifelse(variable=="onlinekommun","no",q_filt)
                                      )




# Zufriedenheit
data_labels <- data_labels %>% mutate(q_text=ifelse(variable=="demokratie","Wie zufrieden oder unzufrieden sind Sie alles in allem mit der Demokratie, so wie sie derzeit in Österreich funktioniert? Sind Sie sehr zufrieden, eher zufrieden, teils-teils, eher unzufrieden oder sehr unzufrieden?",q_text),
                                      q_text=ifelse(variable=="lebensz","Alles in allem betrachtet, wie zufrieden sind Sie derzeit mit Ihrem Leben? Bitte antworten Sie auf einer Skala von 0=äußerst unzufrieden bis 10-=äußerst zufrieden.",q_text),
                                      q_text=ifelse(variable=="blianz_reg","Sind Sie nach heutigem Stand mit der Bilanz, d.h. mit der Arbeit und Leistung, der aktuellen Bundesregierung (also der Koalition aus ÖVP und Grünen) sehr zufrieden, eher zufrieden, teils-teils, eher unzufrieden oder sehr unzufrieden?",q_text),
                                      q_text=ifelse(variable=="zuf_reg_al","Wie zufrieden oder unzufrieden sind Sie nach heutigem Stand mit der Arbeit der Bundesregierung in den folgenden Bereichen? Sind Sie sehr zufrieden, eher zufrieden, teils-teils, eher unzufrieden oder sehr unzufrieden? Bekämpfung der Arbeitslosigkeit. ",q_text),
                                      q_text=ifelse(variable=="zuf_reg_un","Wie zufrieden oder unzufrieden sind Sie nach heutigem Stand mit der Arbeit der Bundesregierung in den folgenden Bereichen? Sind Sie sehr zufrieden, eher zufrieden, teils-teils, eher unzufrieden oder sehr unzufrieden? tützung der kleinen und mittleren Unternehmen",q_text),
                                      q_text=ifelse(variable=="zuf_reg_wi","Wie zufrieden oder unzufrieden sind Sie nach heutigem Stand mit der Arbeit der Bundesregierung in den folgenden Bereichen? Sind Sie sehr zufrieden, eher zufrieden, teils-teils, eher unzufrieden oder sehr unzufrieden? Stützung der Wirtschaft allgemein.",q_text),
                                      
                                      q_text=ifelse(variable=="zuf_fam","Wenn Sie an Ihre gegenwärtige Situation denken, wie zufrieden sind Sie alles in allem mit Ihrem Familienleben? Sehr zufrieden, eher zufrieden, weniger zufrieden, nicht zufrieden oder trifft die Frage nicht zu (keine Familie)?",q_text),
                                      q_text=ifelse(variable=="zuf_par","Wenn Sie an Ihre gegenwärtige Situation denken, wie zufrieden sind Sie alles in allem mit Ihrer Partnerschaft? Sehr zufrieden, eher zufrieden, weniger zufrieden, nicht zufrieden oder trifft die Frage nicht zu (keine Partner/in)?",q_text),
                                      q_text=ifelse(variable=="zuf_ber","Wenn Sie an Ihre gegenwärtige Situation denken, wie zufrieden sind Sie alles in allem mit Ihrem Beruf? Sehr zufrieden, eher zufrieden, weniger zufrieden, nicht zufrieden oder trifft die Frage nicht zu (nicht berufstätig)?",q_text),
                                      q_text=ifelse(variable=="zuf_frz","Wenn Sie an Ihre gegenwärtige Situation denken, wie zufrieden sind Sie alles in allem mit Ihrer Freizeitgestaltung?? Sehr zufrieden, eher zufrieden, weniger zufrieden oder nicht zufrieden?",q_text),
                                      
                                      
                                      
                                      q_cate=ifelse(variable=="demokratie","Zufriedenheit",q_cate),
                                      q_cate=ifelse(variable=="lebensz","Zufriedenheit",q_cate),
                                      q_cate=ifelse(variable=="blianz_reg","Zufriedenheit",q_cate),
                                      q_cate=ifelse(variable=="zuf_reg_al","Zufriedenheit",q_cate),
                                      q_cate=ifelse(variable=="zuf_reg_un","Zufriedenheit",q_cate),
                                      q_cate=ifelse(variable=="zuf_reg_wi","Zufriedenheit",q_cate),
                                      q_cate=ifelse(variable=="zuf_reg_un","Zufriedenheit",q_cate),
                                      q_cate=ifelse(variable=="zuf_fam","Zufriedenheit",q_cate),
                                      q_cate=ifelse(variable=="zuf_par","Zufriedenheit",q_cate),
                                      q_cate=ifelse(variable=="zuf_ber","Zufriedenheit",q_cate),
                                      q_cate=ifelse(variable=="zuf_frz","Zufriedenheit",q_cate),
                                      
                                      q_filt=ifelse(variable=="demokratie","no",q_filt),
                                      q_filt=ifelse(variable=="lebensz","no",q_filt),
                                      q_filt=ifelse(variable=="blianz_reg","no",q_filt),
                                      q_filt=ifelse(variable=="zuf_reg_al","no",q_filt),
                                      q_filt=ifelse(variable=="zuf_reg_un","no",q_filt),
                                      q_filt=ifelse(variable=="zuf_reg_wi","no",q_filt),
                                      q_filt=ifelse(variable=="zuf_reg_un","no",q_filt),
                                      q_filt=ifelse(variable=="zuf_fam","kein Filter aber zusätzliche Ausweichkategorie: Trifft nicht zu (keine Familie/ Partner/in/ nicht berufstätig)",q_filt),
                                      q_filt=ifelse(variable=="zuf_par","kein Filter aber zusätzliche Ausweichkategorie: Trifft nicht zu (keine Familie/ Partner/in/ nicht berufstätig)",q_filt),
                                      q_filt=ifelse(variable=="zuf_ber","kein Filter aber zusätzliche Ausweichkategorie: Trifft nicht zu (keine Familie/ Partner/in/ nicht berufstätig)",q_filt),
                                      q_filt=ifelse(variable=="zuf_frz","no",q_filt)
                                      )




# Zusammenhalt
data_labels <- data_labels %>% mutate(q_text=ifelse(variable=="zus_bestes","Ganz allgemein, wie sehr trifft die folgende Aussage auf die Stimmung in unserer Gesellschaft zu? Trifft sie voll und ganz zu, eher zu, teils-teils, eher nicht zu oder gar nicht zu? Wir geben alle unser Bestes, um die Krisensituation zu überwinden.",q_text),
                                      q_text=ifelse(variable=="zus_einig","Ganz allgemein, wie sehr trifft die folgende Aussage auf die Stimmung in unserer Gesellschaft zu? Trifft sie voll und ganz zu, eher zu, teils-teils, eher nicht zu oder gar nicht zu? Die meisten sind sich einig, dass Zusammenhalt in der aktuellen Krisensituation wichtig ist.",q_text),
                                      q_text=ifelse(variable=="zus_schutzen","Ganz allgemein, wie sehr trifft die folgende Aussage auf die Stimmung in unserer Gesellschaft zu? Trifft sie voll und ganz zu, eher zu, teils-teils, eher nicht zu oder gar nicht zu? Wir rücken in der aktuellen Situation zusammen, um die Schwachen zu schützen.",q_text),
                                                                            
                                      q_cate=ifelse(variable=="zus_bestes","Zusammenhalt",q_cate),
                                      q_cate=ifelse(variable=="zus_einig","Zusammenhalt",q_cate),
                                      q_cate=ifelse(variable=="zus_schutzen","Zusammenhalt",q_cate),
                                      
                                      q_filt=ifelse(variable=="zus_bestes","no",q_filt),
                                      q_filt=ifelse(variable=="zus_einig","no",q_filt),
                                      q_filt=ifelse(variable=="zus_schutzen","no",q_filt)
                                      )




# Corona-Maßnahmen
data_labels <- data_labels %>% mutate(q_text=ifelse(variable=="mas_angemessen","Halten Sie die Reaktion der österreichischen Regierung in Zusammenhang mit dem Coronavirus für nicht ausreichend, angemessen oder zu extrem? Überhaupt nicht ausreichend, eher nicht ausreichend, angemessen, eher zu stark oder zu extrem?",q_text),
                                      q_text=ifelse(variable=="mas_effektiv","Wie effektiv, denken Sie, sind die gesetzten Maßnahmen der österreichischen Regierung bis jetzt, um die Ausbreitung der Krankheit zu verlangsamen? Überhaupt nicht effektiv, eher nicht effektiv, teils effektiv, eher effektiv oder sehr effektiv?",q_text),
                                      q_text=ifelse(variable=="dauer","Und wie lang genau, schätzen Sie, dauert es, bis das Leben in Österreich wieder normal ist? 6 bis 12Monate, 1 bis 1.5 Jahre, 1.5 bis 2 Jahre, 2 bis 3 Jahre, 3 bis 5 Jahre oder mehr als 5 Jahre?",q_text),
                                                                            
                                      q_cate=ifelse(variable=="mas_angemessen","Corona-Maßnahmen",q_cate),
                                      q_cate=ifelse(variable=="mas_effektiv","Corona-Maßnahmen",q_cate),
                                      q_cate=ifelse(variable=="dauer","Corona-Maßnahmen",q_cate),
                                      
                                      q_filt=ifelse(variable=="mas_angemessen","no",q_filt),
                                      q_filt=ifelse(variable=="mas_effektiv","no",q_filt),
                                      q_filt=ifelse(variable=="dauer","no",q_filt)
                                      )





# Vertrauen
data_labels <- data_labels %>% mutate(q_text=ifelse(variable=="ver_gov","Wenn Sie auf die folgende Liste sehen: Haben Sie sehr viel, ziemlich viel, wenig oder überhaupt kein Vertrauen in die jeweils genannten Institutionen im Rahmen der Coronakrise? Bitte antworten Sie auf einer Skala von 0=Überhaupt kein Vertrauen bis 10=sehr viel vertrauen: Die Bundesregierung",q_text),
                                      q_text=ifelse(variable=="ver_ges","Wenn Sie auf die folgende Liste sehen: Haben Sie sehr viel, ziemlich viel, wenig oder überhaupt kein Vertrauen in die jeweils genannten Institutionen im Rahmen der Coronakrise? Bitte antworten Sie auf einer Skala von 0=Überhaupt kein Vertrauen bis 10=sehr viel vertrauen: Das Gesundheitswesen",q_text),
                                      q_text=ifelse(variable=="ver_par","Wenn Sie auf die folgende Liste sehen: Haben Sie sehr viel, ziemlich viel, wenig oder überhaupt kein Vertrauen in die jeweils genannten Institutionen im Rahmen der Coronakrise? Bitte antworten Sie auf einer Skala von 0=Überhaupt kein Vertrauen bis 10=sehr viel vertrauen: Das Parlament",q_text),
                                      q_text=ifelse(variable=="ver_pol","Wenn Sie auf die folgende Liste sehen: Haben Sie sehr viel, ziemlich viel, wenig oder überhaupt kein Vertrauen in die jeweils genannten Institutionen im Rahmen der Coronakrise? Bitte antworten Sie auf einer Skala von 0=Überhaupt kein Vertrauen bis 10=sehr viel vertrauen: Die Polizei",q_text),
                                      q_text=ifelse(variable=="ver_orf","Wenn Sie auf die folgende Liste sehen: Haben Sie sehr viel, ziemlich viel, wenig oder überhaupt kein Vertrauen in die jeweils genannten Institutionen im Rahmen der Coronakrise? Bitte antworten Sie auf einer Skala von 0=Überhaupt kein Vertrauen bis 10=sehr viel vertrauen: Das öffentlich-rechtliche Fernsehen (ORF)",q_text),
                                                                            
                                      q_cate=ifelse(variable=="ver_gov","Vertrauen",q_cate),
                                      q_cate=ifelse(variable=="ver_ges","Vertrauen",q_cate),
                                      q_cate=ifelse(variable=="ver_par","Vertrauen",q_cate),
                                      q_cate=ifelse(variable=="ver_pol","Vertrauen",q_cate),
                                      q_cate=ifelse(variable=="ver_orf","Vertrauen",q_cate),
                                      
                                      q_filt=ifelse(variable=="ver_gov","no",q_filt),
                                      q_filt=ifelse(variable=="ver_ges","no",q_filt),
                                      q_filt=ifelse(variable=="ver_par","no",q_filt),
                                      q_filt=ifelse(variable=="ver_pol","no",q_filt),
                                      q_filt=ifelse(variable=="ver_orf","no",q_filt)
                                      )




# Finanzielle Situation
data_labels <- data_labels %>% mutate(q_text=ifelse(variable=="fin_ausk_akt", "Wie beurteilen Sie die aktuelle finanzielle Situation Ihres Haushalts? Können Sie mit den Haushaltseinkünften sehr gut zurechtkommen, gut zurechtkommen, teils-teils, nur schwer zurechtkommen, nur sehr schwer zurechtkommen?",q_text),
                                      q_text=ifelse(variable=="fin_ausk_yea","Wie wird die finanzielle Situation Ihres Haushalts in Zukunft (in 12 Monaten) im Vergleich zu Ihrer aktuellen Situation sein? Viel besser, etwas besser, gleich bleibend, etwas schlechter, viel schlechter?",q_text),
                                      q_text=ifelse(variable=="eco_ausk_yea","Wie wird die allgemeine Wirtschaftslage in Österreich in Zukunft (in 12 Monaten) im Vergleich zu der aktuellen Situation sein? Viel besser, etwas besser, gleich bleibend, etwas schlechter, viel schlechter?",q_text),
                                                                            
                                      q_cate=ifelse(variable=="fin_ausk_akt","Finanzielle Situation",q_cate),
                                      q_cate=ifelse(variable=="fin_ausk_yea","Finanzielle Situation",q_cate),
                                      q_cate=ifelse(variable=="eco_ausk_yea","Finanzielle Situation",q_cate),
                                      
                                      q_filt=ifelse(variable=="fin_ausk_akt","no",q_filt),
                                      q_filt=ifelse(variable=="fin_ausk_yea","no",q_filt),
                                      q_filt=ifelse(variable=="eco_ausk_yea","no",q_filt)
                                      )


# Coronakrise: Einstellungen
data_labels <- data_labels %>% mutate(
                                      q_text=ifelse(variable=="skept_lebens","Bitte geben Sie an, ob die jeweilige Aussage Ihrer Meinung nach sehr zutrifft, eher zutrifft, teils-teils zutrifft, eher nicht zutrifft oder gar nicht zutrifft: Um die Corona-Krise einzudämmen, sind die meisten in meinem persönlichen Umfeld bereit, ihre Lebensweise zu ändern.",q_text),
                                      q_text=ifelse(variable=="skept_wichti","Bitte geben Sie an, ob die jeweilige Aussage Ihrer Meinung nach sehr zutrifft, eher zutrifft, teils-teils zutrifft, eher nicht zutrifft oder gar nicht zutrifft: Es gibt Wichtigeres im Leben als die Corona-Krise.",q_text),
                                      q_text=ifelse(variable=="skept_behaup" , "Bitte geben Sie an, ob die jeweilige Aussage Ihrer Meinung nach sehr zutrifft, eher zutrifft, teils-teils zutrifft, eher nicht zutrifft oder gar nicht zutrifft: Viele Behauptungen bezüglich der Corona-Krise, die man von anderen so hört, sind übertrieben. " , q_text),
                                      q_text=ifelse(variable=="skept_andere", "Bitte geben Sie an, ob die jeweilige Aussage Ihrer Meinung nach sehr zutrifft, eher zutrifft, teils-teils zutrifft, eher nicht zutrifft oder gar nicht zutrifft: olange andere ihr Verhalten nicht ändern, muss ich mein Verhalten bezüglich der Corona-Krise auch nicht ändern.",q_text),
                                      q_text=ifelse(variable=="skept_fehler","Bitte geben Sie an, ob die jeweilige Aussage Ihrer Meinung nach sehr zutrifft, eher zutrifft, teils-teils zutrifft, eher nicht zutrifft oder gar nicht zutrifft: s war ein Fehler, all diese Maßnahmen zur Eindämmung des Coronavirus zu erlassen.",q_text),
                                      
                                      q_text=ifelse(variable=="skept_uebert","Bitte geben Sie an, ob die jeweilige Aussage Ihrer Meinung nach sehr zutrifft, eher zutrifft, teils-teils zutrifft, eher nicht zutrifft oder gar nicht zutrifft: Was die Regierung über die gesundheitliche Gefahr des Coronavirus sagt, ist übertrieben.",q_text),
                                      q_text=ifelse(variable=="skept_grippe","Bitte geben Sie an, ob die jeweilige Aussage Ihrer Meinung nach sehr zutrifft, eher zutrifft, teils-teils zutrifft, eher nicht zutrifft oder gar nicht zutrifft: Das Coronavirus ist gefährlicher als eine normale Grippe.",q_text),
                                      q_text=ifelse(variable=="skept_gerech","Bitte geben Sie an, ob die jeweilige Aussage Ihrer Meinung nach sehr zutrifft, eher zutrifft, teils-teils zutrifft, eher nicht zutrifft oder gar nicht zutrifft: Alles in allem empfinde ich die Corona-Maßnahmen als gerecht.",q_text),
                                      
                                      
                                      q_text=ifelse(variable=="tax_gleich","Bitte geben Sie an, wie stark die folgende Aussage Ihrer Meinung nach zutrifft oder nicht zutrifft Trifft sie voll und ganz zu, eher zu, teils-teils, eher nicht zu oder gar nicht zu? Alle Personen sollten im gleichen Ausmaß zur Finanzierung der Krise beitragen.",q_text),
                                      q_text=ifelse(variable=="tax_ineq","Bitte geben Sie an, wie stark die folgende Aussage Ihrer Meinung nach zutrifft oder nicht zutrifft Trifft sie voll und ganz zu, eher zu, teils-teils, eher nicht zu oder gar nicht zu? Die Kluft zwischen Arm und Reich in Österreich wird sich in Zukunft durch die Krise verstärken.",q_text),
                                      q_text=ifelse(variable=="tax_hurt","Bitte geben Sie an, wie stark die folgende Aussage Ihrer Meinung nach zutrifft oder nicht zutrifft Trifft sie voll und ganz zu, eher zu, teils-teils, eher nicht zu oder gar nicht zu? Die Einführung von neuen Steuern ist schädlich für den Wirtschaftsstandort Österreich.",q_text),
                                      q_text=ifelse(variable=="tax_quarant","Bitte geben Sie an, wie stark die folgende Aussage Ihrer Meinung nach zutrifft oder nicht zutrifft Trifft sie voll und ganz zu, eher zu, teils-teils, eher nicht zu oder gar nicht zu? Die Ausgangsbeschränkungen treffen Personen mit niedrigem Einkommen härter als Personen mit hohem Einkommen.",q_text),
   
                                      q_text=ifelse(variable=="kaufen_haus","Glauben Sie, dass jetzt ein guter oder schlechter Zeitpunkt ist, um größere Haushaltsgegenstände wie Möbel, einen Kühlschrank, einen Herd, einen Fernseher und solche Dinge zu kaufen?",q_text),
                                                                         
                                      
                                      q_cate=ifelse(variable=="skept_lebens","Coronakrise: Einstellungen",q_cate),
                                      q_cate=ifelse(variable=="skept_wichti","Coronakrise: Einstellungen",q_cate),
                                      q_cate=ifelse(variable=="skept_behaup","Coronakrise: Einstellungen",q_cate),
                                      q_cate=ifelse(variable=="skept_andere","Coronakrise: Einstellungen",q_cate),
                                      q_cate=ifelse(variable=="skept_fehler","Coronakrise: Einstellungen",q_cate),
                                      q_cate=ifelse(variable=="skept_uebert","Coronakrise: Einstellungen",q_cate),
                                      q_cate=ifelse(variable=="skept_grippe","Coronakrise: Einstellungen",q_cate),
                                      q_cate=ifelse(variable=="skept_gerech","Coronakrise: Einstellungen",q_cate),
                                      q_cate=ifelse(variable=="tax_gleich","Coronakrise: Einstellungen",q_cate),
                                      q_cate=ifelse(variable=="tax_ineq","Coronakrise: Einstellungen",q_cate),
                                      q_cate=ifelse(variable=="tax_hurt","Coronakrise: Einstellungen",q_cate),
                                      q_cate=ifelse(variable=="tax_quarant","Coronakrise: Einstellungen",q_cate),
                                      
                                      q_filt=ifelse(variable=="skept_lebens","no",q_filt),
                                      q_filt=ifelse(variable=="skept_wichti","no",q_filt),
                                      q_filt=ifelse(variable=="skept_behaup","no",q_filt),
                                      q_filt=ifelse(variable=="skept_andere","no",q_filt),
                                      q_filt=ifelse(variable=="skept_fehler","no",q_filt),
                                      q_filt=ifelse(variable=="skept_uebert","no",q_filt),
                                      q_filt=ifelse(variable=="skept_grippe","no",q_filt),
                                      q_filt=ifelse(variable=="skept_gerech","no",q_filt),
                                      q_filt=ifelse(variable=="tax_gleich","no",q_filt),
                                      q_filt=ifelse(variable=="tax_ineq","no",q_filt),
                                      q_filt=ifelse(variable=="tax_hurt","no",q_filt),
                                      q_filt=ifelse(variable=="tax_quarant","no",q_filt)
                                      )



# Finanzentscheidungen
data_labels <- data_labels %>% mutate(
                                      q_text=ifelse(variable=="zeitp_spar","Glauben Sie, dass für Sie persönlich jetzt ein guter oder schlechter Zeitpunkt ist,	um Geld zu sparen oder auf dem Konto zu belassen?",q_text),
                                      q_text=ifelse(variable=="zeitp_inve","Glauben Sie, dass für Sie persönlich jetzt ein guter oder schlechter Zeitpunkt ist,	um Geld zu investieren (in Aktien, Anleihen, Fonds, etc.)?",q_text),
                                      q_text=ifelse(variable=="zeitp_lieg","Glauben Sie, dass für Sie persönlich jetzt ein guter oder schlechter Zeitpunkt ist,	um Liegenschaften zu erwerben (Wohnungen, Häuser, Grundstücke, etc.)?",q_text),
                                      q_text=ifelse(variable=="zeitp_ausg","Glauben Sie, dass für Sie persönlich jetzt ein guter oder schlechter Zeitpunkt ist,	um Geld auszugeben?
",q_text),
                                      q_text=ifelse(variable=="zeitp_kred","Glauben Sie, dass für Sie persönlich jetzt ein guter oder schlechter Zeitpunkt ist,	um einen Kredit aufzunehmen?
 ",q_text),
                                      q_text=ifelse(variable=="kaufen_haus","Glauben Sie, dass jetzt ein guter oder schlechter Zeitpunkt ist, um größere Haushaltsgegenstände wie Möbel, einen Kühlschrank, einen Herd, einen Fernseher und solche Dinge zu kaufen?",q_text),
                                           
                                    
                                      q_cate=ifelse(variable=="zeitp_spar","Finanzentscheidungen",q_cate),
                                      q_cate=ifelse(variable=="zeitp_inve","Finanzentscheidungen",q_cate),
                                      q_cate=ifelse(variable=="zeitp_lieg","Finanzentscheidungen",q_cate),
                                      q_cate=ifelse(variable=="zeitp_ausg","Finanzentscheidungen",q_cate),
                                      q_cate=ifelse(variable=="zeitp_kred","Finanzentscheidungen",q_cate),
                                      q_cate=ifelse(variable=="kaufen_haus","Finanzentscheidungen",q_cate),

                                      q_filt=ifelse(variable=="zeitp_spar","no",q_filt),
                                      q_filt=ifelse(variable=="zeitp_inve","no",q_filt),
                                      q_filt=ifelse(variable=="zeitp_lieg","no",q_filt),
                                      q_filt=ifelse(variable=="zeitp_ausg","no",q_filt),
                                      q_filt=ifelse(variable=="zeitp_kred","no",q_filt),
                                      q_filt=ifelse(variable=="kaufen_haus","no",q_filt)
                                      )





# Ansteckungsgefahr
data_labels <- data_labels %>% mutate(
                                      q_text=ifelse(variable=="anst_rest","Wie hoch schätzen Sie derzeit die Gefahr der Ansteckung mit dem Coronavirus an den folgenden Orten ein? Ist die Gefahr sehr groß, groß, mittelmäßig, klein oder sehr klein? Restaurants, Cafés und Bars.",q_text),
                                      q_text=ifelse(variable=="anst_oeff","Wie hoch schätzen Sie derzeit die Gefahr der Ansteckung mit dem Coronavirus an den folgenden Orten ein? Ist die Gefahr sehr groß, groß, mittelmäßig, klein oder sehr klein? Öffentliche Verkehrsmittel.",q_text),
                                      q_text=ifelse(variable=="anst_arbe","Wie hoch schätzen Sie derzeit die Gefahr der Ansteckung mit dem Coronavirus an den folgenden Orten ein? Ist die Gefahr sehr groß, groß, mittelmäßig, klein oder sehr klein? Ihrer Arbeitsstätte.",q_text),
                                      q_text=ifelse(variable=="anst_schu","Wie hoch schätzen Sie derzeit die Gefahr der Ansteckung mit dem Coronavirus an den folgenden Orten ein? Ist die Gefahr sehr groß, groß, mittelmäßig, klein oder sehr klein? Schulen und Kindergärten.",q_text),
                                      q_text=ifelse(variable=="anst_park","Wie hoch schätzen Sie derzeit die Gefahr der Ansteckung mit dem Coronavirus an den folgenden Orten ein? Ist die Gefahr sehr groß, groß, mittelmäßig, klein oder sehr klein? Öffentliche Parks und Spielplätze.",q_text),
                                      q_text=ifelse(variable=="anst_arzt","Wie hoch schätzen Sie derzeit die Gefahr der Ansteckung mit dem Coronavirus an den folgenden Orten ein? Ist die Gefahr sehr groß, groß, mittelmäßig, klein oder sehr klein? Arzt.",q_text),
                                      q_text=ifelse(variable=="anst_fami","Wie hoch schätzen Sie derzeit die Gefahr der Ansteckung mit dem Coronavirus an den folgenden Orten ein? Ist die Gefahr sehr groß, groß, mittelmäßig, klein oder sehr klein? Familienfeier.",q_text),
                                      q_text=ifelse(variable=="anst_freu","Wie hoch schätzen Sie derzeit die Gefahr der Ansteckung mit dem Coronavirus an den folgenden Orten ein? Ist die Gefahr sehr groß, groß, mittelmäßig, klein oder sehr klein?  Treffen von Freunden Zuhause.",q_text),
                                    
                                      q_cate=ifelse(variable=="anst_rest","Ansteckungsgefahr",q_cate),
                                      q_cate=ifelse(variable=="anst_oeff","Ansteckungsgefahr",q_cate),
                                      q_cate=ifelse(variable=="anst_arbe","Ansteckungsgefahr",q_cate),
                                      q_cate=ifelse(variable=="anst_schu","Ansteckungsgefahr",q_cate),
                                      q_cate=ifelse(variable=="anst_park","Ansteckungsgefahr",q_cate),
                                      q_cate=ifelse(variable=="anst_arzt","Ansteckungsgefahr",q_cate),
                                      q_cate=ifelse(variable=="anst_fami","Ansteckungsgefahr",q_cate),
                                      q_cate=ifelse(variable=="anst_freu","Ansteckungsgefahr",q_cate),
                                      
                                      q_filt=ifelse(variable=="anst_rest","no",q_filt),
                                      q_filt=ifelse(variable=="anst_oeff","no",q_filt),
                                      q_filt=ifelse(variable=="anst_arbe","erwerbstätig = ja",q_filt),
                                      q_filt=ifelse(variable=="anst_schu","no",q_filt),
                                      q_filt=ifelse(variable=="anst_park","no",q_filt),
                                      q_filt=ifelse(variable=="anst_arzt","no",q_filt),
                                      q_filt=ifelse(variable=="anst_fami","no",q_filt),
                                      q_filt=ifelse(variable=="anst_freu","no",q_filt)
                                      )


# Testen und Impfen: Einstellungen
data_labels <- data_labels %>% mutate(
                                      q_text=ifelse(variable=="mastest_eff","Was denken Sie, inwiefern trifft die folgende Aussage in Zusammenhang mit den Coronavirus-Tests zu? Trifft sie voll und ganz zu, eher zu, teils-teils, eher nicht zu oder gar nicht zu? Die Tests sind eine effektive Maßnahme zur Eindämmung der Corona-Krise.",q_text),
                                      q_text=ifelse(variable=="mastest_zuv","Was denken Sie, inwiefern trifft die folgende Aussage in Zusammenhang mit den Coronavirus-Tests zu? Trifft sie voll und ganz zu, eher zu, teils-teils, eher nicht zu oder gar nicht zu? Das Ergebnis der Tests ist zuverlässig.",q_text),
                                      q_text=ifelse(variable=="mastest_tre","Was denken Sie, inwiefern trifft die folgende Aussage in Zusammenhang mit den Coronavirus-Tests zu? Trifft sie voll und ganz zu, eher zu, teils-teils, eher nicht zu oder gar nicht zu? Ein negatives Testergebnis bedeutet, dass ich wieder mehrere Personen treffen kann.",q_text),
                                      q_text=ifelse(variable=="mastest_str","Was denken Sie, inwiefern trifft die folgende Aussage in Zusammenhang mit den Coronavirus-Tests zu? Trifft sie voll und ganz zu, eher zu, teils-teils, eher nicht zu oder gar nicht zu? Für Personen, die sich nicht testen lassen, sollten strengere Maßnahmen gelten.",q_text),
                                      q_text=ifelse(variable=="mastest_mot","Was denken Sie, inwiefern trifft die folgende Aussage in Zusammenhang mit den Coronavirus-Tests zu? Trifft sie voll und ganz zu, eher zu, teils-teils, eher nicht zu oder gar nicht zu? Es ist für alle möglich, sich schnell testen zu lassen.",q_text),
                                      q_text=ifelse(variable=="impf_pfb","Bitte geben Sie an, ob die jeweilige Aussage Ihrer Meinung nach sehr zutrifft, eher zutrifft, teils-teils zutrifft, eher nicht zutrifft oder gar nicht zutrifft:	Es sollte eine Impfpflicht für Berufsgruppen mit hohem Ansteckungsrisiko geben.",q_text),
                                      q_text=ifelse(variable=="impf_gra","Bitte geben Sie an, ob die jeweilige Aussage Ihrer Meinung nach sehr zutrifft, eher zutrifft, teils-teils zutrifft, eher nicht zutrifft oder gar nicht zutrifft:	Der Impfstoff sollte gratis zur Verfügung gestellt werden.",q_text),
                                      q_text=ifelse(variable=="impf_pfl","Bitte geben Sie an, ob die jeweilige Aussage Ihrer Meinung nach sehr zutrifft, eher zutrifft, teils-teils zutrifft, eher nicht zutrifft oder gar nicht zutrifft:	Es sollte eine Impfpflicht für alle geben.",q_text),
                                      q_text=ifelse(variable=="impf_kin","XXXXX???????",q_text),
                                      q_text=ifelse(variable=="impf_soz","Bitte geben Sie an, ob die jeweilige Aussage Ihrer Meinung nach sehr zutrifft, eher zutrifft, teils-teils zutrifft, eher nicht zutrifft oder gar nicht zutrifft:	Die meisten Personen in meinem näheren Umfeld sind bereit, sich impfen zu lassen.",q_text),
                                    
                                      q_cate=ifelse(variable=="mastest_eff","Testen und Impfen: Einstellungen",q_cate),
                                      q_cate=ifelse(variable=="mastest_zuv","Testen und Impfen: Einstellungen",q_cate),
                                      q_cate=ifelse(variable=="mastest_tre","Testen und Impfen: Einstellungen",q_cate),
                                      q_cate=ifelse(variable=="mastest_str","Testen und Impfen: Einstellungen",q_cate),
                                      q_cate=ifelse(variable=="mastest_mot","Testen und Impfen: Einstellungen",q_cate),
                                      q_cate=ifelse(variable=="impf_pfb","Testen und Impfen: Einstellungen",q_cate),
                                      q_cate=ifelse(variable=="impf_gra","Testen und Impfen: Einstellungen",q_cate),
                                      q_cate=ifelse(variable=="impf_pfl","Testen und Impfen: Einstellungen",q_cate),
                                      q_cate=ifelse(variable=="impf_kin","Testen und Impfen: Einstellungen",q_cate),
                                      q_cate=ifelse(variable=="impf_soz","Testen und Impfen: Einstellungen",q_cate),
                                      
                                      q_filt=ifelse(variable=="mastest_eff","no",q_filt),
                                      q_filt=ifelse(variable=="mastest_zuv","no",q_filt),
                                      q_filt=ifelse(variable=="mastest_tre","no",q_filt),
                                      q_filt=ifelse(variable=="mastest_str","no",q_filt),
                                      q_filt=ifelse(variable=="mastest_mot","no",q_filt),
                                      q_filt=ifelse(variable=="impf_pfb","no",q_filt),
                                      q_filt=ifelse(variable=="impf_gra","no",q_filt),
                                      q_filt=ifelse(variable=="impf_pfl","no",q_filt),
                                      q_filt=ifelse(variable=="impf_kin","Kinder <=14j.=ja",q_filt),
                                      q_filt=ifelse(variable=="impf_soz","no",q_filt)
                                      )



# Eigenes Verhalten
data_labels <- data_labels %>% mutate(
                                      q_text=ifelse(variable=="sozialn_verh_eig_abs","Denken Sie im Folgenden an Ihr persönliches Verhalten in der letzten Woche. Bitte geben Sie an, wie oft Sie sich wie folgt verhalten haben. Haben Sie sich nahezu immer, meistens, manchmal, selten oder nahezu nie daran gehalten? Sie halten im öffentlichen Raum immer mindestens 1m Abstand von Menschen, die nicht mit Ihnen im Haushalt leben.",q_text),
                                      q_text=ifelse(variable=="sozialn_verh_eig_hau","Denken Sie im Folgenden an Ihr persönliches Verhalten in der letzten Woche. Bitte geben Sie an, wie oft Sie sich wie folgt verhalten haben. Haben Sie sich nahezu immer, meistens, manchmal, selten oder nahezu nie daran gehalten? Sie bleiben zu Hause, außer für Notwendigkeiten.",q_text),
                                      q_text=ifelse(variable=="sozialn_verh_eig_sch","Denken Sie im Folgenden an Ihr persönliches Verhalten in der letzten Woche. Bitte geben Sie an, wie oft Sie sich wie folgt verhalten haben. Haben Sie sich nahezu immer, meistens, manchmal, selten oder nahezu nie daran gehalten? Sie tragen immer Schutzmasken, wenn Sie sich im öffentlichen Raum bewegen.",q_text),
                                      q_text=ifelse(variable=="sozialn_verh_eig_ver","Denken Sie im Folgenden an Ihr persönliches Verhalten in der letzten Woche. Bitte geben Sie an, wie oft Sie sich wie folgt verhalten haben. Haben Sie sich nahezu immer, meistens, manchmal, selten oder nahezu nie daran gehalten? Sie vermeiden Aktivitäten im Haushalt und in der Freizeit, die zu Verletzungen oder Krankheiten führen könnten, um das Gesundheitssystem nicht zu belasten.",q_text),
                                      q_text=ifelse(variable=="sozkont","Wie häufig haben Sie sich mit Menschen, die Ihnen nahestehen, in der letzten Woche ausgetauscht (oder Kontakt gehalten)? Mehrmals täglich, einmal täglich, mehrmals in der Woche, einmal in der Woche oder gar nicht/ nie?
",q_text),
                                           
                                    
                                      q_cate=ifelse(variable=="sozialn_verh_eig_abs","Eigenes Verhalten",q_cate),
                                      q_cate=ifelse(variable=="sozialn_verh_eig_hau","Eigenes Verhalten",q_cate),
                                      q_cate=ifelse(variable=="sozialn_verh_eig_sch","Eigenes Verhalten",q_cate),
                                      q_cate=ifelse(variable=="sozialn_verh_eig_ver","Eigenes Verhalten",q_cate),
                                      q_cate=ifelse(variable=="sozkont","Eigenes Verhalten",q_cate),

                                      q_filt=ifelse(variable=="sozialn_verh_eig_abs","no",q_filt),
                                      q_filt=ifelse(variable=="sozialn_verh_eig_hau","no",q_filt),
                                      q_filt=ifelse(variable=="sozialn_verh_eig_sch","no",q_filt),
                                      q_filt=ifelse(variable=="sozialn_verh_eig_ver","no",q_filt),
                                      q_filt=ifelse(variable=="sozkont","no",q_filt)
                                      )



# Gesellschaftspolitische Einstellungen
data_labels <- data_labels %>% mutate(
                                      q_text=ifelse(variable=="issue_ungl","Man kann zu verschiedenen politischen Themen unterschiedliche Meinungen haben. Treffen die folgenden Aussagen Ihrer Meinung nach sehr zu, eher zu, teils-teils zu, treffen sie eher nicht zu oder treffen sie überhaupt nicht zu? Die Politik muss die soziale Ungleichheit bekämpfen.",q_text),
                                      q_text=ifelse(variable=="issue_faul","Man kann zu verschiedenen politischen Themen unterschiedliche Meinungen haben. Treffen die folgenden Aussagen Ihrer Meinung nach sehr zu, eher zu, teils-teils zu, treffen sie eher nicht zu oder treffen sie überhaupt nicht zu? Der Sozialstaat macht Menschen träge und faul.",q_text),
                                      q_text=ifelse(variable=="issue_albe","Man kann zu verschiedenen politischen Themen unterschiedliche Meinungen haben. Treffen die folgenden Aussagen Ihrer Meinung nach sehr zu, eher zu, teils-teils zu, treffen sie eher nicht zu oder treffen sie überhaupt nicht zu? Die Arbeitslosigkeit muss bekämpft werden, auch wenn das hohe Staatsschulden bedeutet.",q_text),
                                      q_text=ifelse(variable=="issue_wirt","Man kann zu verschiedenen politischen Themen unterschiedliche Meinungen haben. Treffen die folgenden Aussagen Ihrer Meinung nach sehr zu, eher zu, teils-teils zu, treffen sie eher nicht zu oder treffen sie überhaupt nicht zu? Die Politik soll sich aus der Wirtschaft heraushalten.",q_text),
                                      q_text=ifelse(variable=="issue_frau","Man kann zu verschiedenen politischen Themen unterschiedliche Meinungen haben. Treffen die folgenden Aussagen Ihrer Meinung nach sehr zu, eher zu, teils-teils zu, treffen sie eher nicht zu oder treffen sie überhaupt nicht zu? Frauen sollen bei Bewerbungen und Beförderungen bei gleicher Qualifikation bevorzugt werden.",q_text),
                                      q_text=ifelse(variable=="issue_poli","Man kann zu verschiedenen politischen Themen unterschiedliche Meinungen haben. Treffen die folgenden Aussagen Ihrer Meinung nach sehr zu, eher zu, teils-teils zu, treffen sie eher nicht zu oder treffen sie überhaupt nicht zu? Die Befugnisse der Polizei müssen ausgeweitet werden, um für Recht und Ordnung zu sorgen.",q_text),
                                      q_text=ifelse(variable=="issue_zuwa","Man kann zu verschiedenen politischen Themen unterschiedliche Meinungen haben. Treffen die folgenden Aussagen Ihrer Meinung nach sehr zu, eher zu, teils-teils zu, treffen sie eher nicht zu oder treffen sie überhaupt nicht zu? Zuwanderung nach Österreich sollte nur in absoluten Ausnahmefällen möglich sein.",q_text),
                                      q_text=ifelse(variable=="issue_umwe","Man kann zu verschiedenen politischen Themen unterschiedliche Meinungen haben. Treffen die folgenden Aussagen Ihrer Meinung nach sehr zu, eher zu, teils-teils zu, treffen sie eher nicht zu oder treffen sie überhaupt nicht zu? Die Umwelt muss um jeden Preis geschützt werden, auch wenn das für den Einzelnen teuer wird.",q_text),
                                      q_text=ifelse(variable=="issue_eink","Man kann zu verschiedenen politischen Themen unterschiedliche Meinungen haben. Treffen die folgenden Aussagen Ihrer Meinung nach sehr zu, eher zu, teils-teils zu, treffen sie eher nicht zu oder treffen sie überhaupt nicht zu? Die Einkommensunterschiede in Österreich sind zu groß.",q_text),
                                      q_text=ifelse(variable=="issue_gena","Man kann zu verschiedenen politischen Themen unterschiedliche Meinungen haben. Treffen die folgenden Aussagen Ihrer Meinung nach sehr zu, eher zu, teils-teils zu, treffen sie eher nicht zu oder treffen sie überhaupt nicht zu? Die Jungen von heute werden alles in allem ein besseres Leben haben als ihre Eltern.",q_text),
                                      q_text=ifelse(variable=="issue_redu","Man kann zu verschiedenen politischen Themen unterschiedliche Meinungen haben. Treffen die folgenden Aussagen Ihrer Meinung nach sehr zu, eher zu, teils-teils zu, treffen sie eher nicht zu oder treffen sie überhaupt nicht zu? Der Staat sollte Maßnahmen ergreifen, um Einkommensunterschiede zu reduzieren.",q_text),
                                      q_text=ifelse(variable=="welfshov_such","Bitte geben Sie an, wie sehr Sie den folgenden Aussagen über Leute in Österreich zustimmen oder wie sehr Sie diese ablehnen: Die meisten Arbeitslosen suchen nicht wirklich nach einer Arbeitsstelle.",q_text),
                                      q_text=ifelse(variable=="welfshov_sozl","Es gelingt vielen Leuten, Sozialleistungen zu erhalten, die keinen Anspruch darauf haben.",q_text),
                                      q_text=ifelse(variable=="welfshov_zust","Viele Leute mit geringem Einkommen erhalten weniger Sozialleistungen, als ihnen gesetzlich zustehen.",q_text),
                              
                                    
                                      q_cate=ifelse(variable=="issue_ungl","Gesellschaftspolitische Einstellungen",q_cate),
                                      q_cate=ifelse(variable=="issue_faul","Gesellschaftspolitische Einstellungen",q_cate),
                                      q_cate=ifelse(variable=="issue_albe","Gesellschaftspolitische Einstellungen",q_cate),
                                      q_cate=ifelse(variable=="issue_wirt","Gesellschaftspolitische Einstellungen",q_cate),
                                      q_cate=ifelse(variable=="issue_frau","Gesellschaftspolitische Einstellungen",q_cate),
                                      q_cate=ifelse(variable=="issue_poli","Gesellschaftspolitische Einstellungen",q_cate),
                                      q_cate=ifelse(variable=="issue_zuwa","Gesellschaftspolitische Einstellungen",q_cate),
                                      q_cate=ifelse(variable=="issue_umwe","Gesellschaftspolitische Einstellungen",q_cate),
                                      q_cate=ifelse(variable=="issue_eink","Gesellschaftspolitische Einstellungen",q_cate),
                                      q_cate=ifelse(variable=="issue_gena","Gesellschaftspolitische Einstellungen",q_cate),
                                      q_cate=ifelse(variable=="issue_redu","Gesellschaftspolitische Einstellungen",q_cate),
                                      q_cate=ifelse(variable=="welfshov_such","Gesellschaftspolitische Einstellungen",q_cate),
                                      q_cate=ifelse(variable=="welfshov_zust","Gesellschaftspolitische Einstellungen",q_cate),
                                      q_cate=ifelse(variable=="welfshov_sozl","Gesellschaftspolitische Einstellungen",q_cate),
                                      
                                      q_filt=ifelse(variable=="issue_ungl","no",q_filt),
                                      q_filt=ifelse(variable=="issue_faul","no",q_filt),
                                      q_filt=ifelse(variable=="issue_albe","no",q_filt),
                                      q_filt=ifelse(variable=="issue_wirt","no",q_filt),
                                      q_filt=ifelse(variable=="issue_frau","no",q_filt),
                                      q_filt=ifelse(variable=="issue_poli","no",q_filt),
                                      q_filt=ifelse(variable=="issue_zuwa","no",q_filt),
                                      q_filt=ifelse(variable=="issue_umwe","no",q_filt),
                                      q_filt=ifelse(variable=="issue_eink","no",q_filt),
                                      q_filt=ifelse(variable=="issue_gena","no",q_filt),
                                      q_filt=ifelse(variable=="issue_redu","no",q_filt),
                                      q_filt=ifelse(variable=="welfshov_such","no",q_filt),
                                      q_filt=ifelse(variable=="welfshov_zust","no",q_filt),
                                      q_filt=ifelse(variable=="welfshov_sozl","no",q_filt)
                                      )

write_csv(data_labels, "./output/tables/data_labels_cq.csv", na = "NA")

```

