channels:
  - conda-forge
dependencies:
  - r-base=4.0.2
  - r-tidyr
  - r-plotly
  - r-dplyr
  - r-stringr
  - r-forcats
  - r-base64enc
  - r-rmarkdown
  - r-httr
  - r-readr
  - r-shiny
  - r-flexdashboard